import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          {/* Main wrapper div with min-h-screen */}
          <div className="flex flex-col min-h-screen justify-between items-center w-full">
            {/* Main content with flex-grow to fill space */}
            <main className="flex flex-grow flex-col justify-center items-center w-full">
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
