  import type { Metadata } from "next";
  import localFont from "next/font/local";
  import "./globals.css";
  import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
  import { AppSidebar } from "@/components/ui/app-sidebar"

  const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
  });
  const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      // idk dont delete the html tag
      <html lang="en">                                                       
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <div className="flex flex-grow flex-col justify-center items-center">
            {children}
          </div>
          </SidebarProvider>
        </body>
      </html>
    );
  }
